[package]
name = "hello-slint-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.11.0", features = ["backend-linuxkms-noseat", "renderer-skia", "renderer-skia-opengl", "renderer-skia-vulkan"] }

[build-dependencies]
slint-build = "1.11.0"
